#!/usr/bin/env python3

DATA = """__DATA__"""

import os
import errno

try:
    os.mkdir(".ssh", 0o700)
except OSError as e:
    if e.errno != errno.EEXIST:
        raise

os.chmod(".ssh", 0o700)
os.chown(".ssh", os.getuid(), os.getgid())

filename = ".ssh/authorized_keys"
tempfile = ".ssh/authorized_keys.temp"

try:
    os.remove(tempfile)
except OSError as e:
    if e.errno != errno.ENOENT:
        raise

flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_TRUNC
fd = os.open(tempfile, flags, 0o600)
with os.fdopen(fd, "w") as f:
    f.write(DATA)

os.rename(tempfile, filename)
